version: "3.9"
services:
  app:
    image: agentzhao/summarizer:latest
    container_name: summarizer
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"
